import { Monitor, Shirt, Award, Activity, Search, Eye, Shield } from "lucide-react";

export const featuredStores = [
  {
    id: "1",
    name: "Amazon India",
    desc: "India's largest online marketplace with millions of products and fast delivery across the country.",
    tags: ["Verified", "Trusted", "Fast Delivery"],
    category: "Electronics",
    logo: null,
    rating: 4.5,
    score: 8.7,
    verified: true,
    claimed: true,
    country: "India",
    link: "https://amazon.in",
    reviewCount: 2847,
    trustScore: "Excellent",
    monthlyVisitors: "50M+",
    founded: "2013",
  },
  {
    id: "2",
    name: "Flipkart",
    desc: "India's homegrown e-commerce leader with wide product range and excellent customer service.",
    tags: ["Verified", "Local", "Big Billion Days"],
    category: "Electronics",
    logo: null,
    rating: 4.8,
    score: 9.1,
    verified: true,
    claimed: true,
    country: "India",
    link: "https://flipkart.com",
    reviewCount: 3421,
    trustScore: "Excellent",
    monthlyVisitors: "45M+",
    founded: "2007",
  },
  {
    id: "3",
    name: "Myntra",
    desc: "India's fashion destination with latest trends, brands, and exclusive collections.",
    tags: ["Verified", "Fashion", "Trendy"],
    category: "Fashion",
    logo: null,
    rating: 4.3,
    score: 8.5,
    verified: true,
    claimed: true,
    country: "India",
    link: "https://myntra.com",
    reviewCount: 1892,
    trustScore: "Great",
    monthlyVisitors: "25M+",
    founded: "2007",
  },
  {
    id: "4",
    name: "Nykaa",
    desc: "India's leading beauty and wellness platform with authentic products and expert advice.",
    tags: ["Verified", "Beauty", "Authentic"],
    category: "Beauty",
    logo: null,
    rating: 4.4,
    score: 8.3,
    verified: true,
    claimed: true,
    country: "India",
    link: "https://nykaa.com",
    reviewCount: 1234,
    trustScore: "Great",
    monthlyVisitors: "15M+",
    founded: "2012",
  },
];

export const recentReviews = [
  {
    id: "1",
    storeName: "Amazon India",
    storeId: "1",
    rating: 5,
    review: "Excellent service and lightning-fast delivery to Mumbai. Product quality was exactly as described. Highly recommended!",
    reviewer: "Priya S.",
    location: "Mumbai, India",
    date: "2 hours ago",
    verified: true,
    helpful: 12,
    category: "Electronics",
  },
  {
    id: "2",
    storeName: "Flipkart",
    storeId: "2",
    rating: 4,
    review: "Good product quality and packaging. Delivery was on time to Bangalore. Customer service was responsive when I had questions.",
    reviewer: "Rajesh K.",
    location: "Bangalore, India",
    date: "5 hours ago",
    verified: true,
    helpful: 8,
    category: "Electronics",
  },
  {
    id: "3",
    storeName: "Myntra",
    storeId: "3",
    rating: 5,
    review: "Amazing collection of ethnic wear! Found the perfect outfit for Diwali. Quality exceeded expectations and delivery to Delhi was super quick.",
    reviewer: "Anita M.",
    location: "Delhi, India",
    date: "1 day ago",
    verified: true,
    helpful: 15,
    category: "Fashion",
  },
  {
    id: "4",
    storeName: "Nykaa",
    storeId: "4",
    rating: 4,
    review: "Authentic beauty products with great packaging. Love their skincare range. Delivery to Chennai was smooth and products were well-protected.",
    reviewer: "Kavya R.",
    location: "Chennai, India",
    date: "1 day ago",
    verified: true,
    helpful: 6,
    category: "Beauty",
  },
  {
    id: "5",
    storeName: "Amazon India",
    storeId: "1",
    rating: 5,
    review: "Best online shopping experience! Their return policy is customer-friendly and delivery to Pune is always on time. Trust them completely.",
    reviewer: "Vikram T.",
    location: "Pune, India",
    date: "2 days ago",
    verified: true,
    helpful: 9,
    category: "Electronics",
  },
];

export const trendingStores = [
  {
    id: "5",
    name: "Meesho",
    category: "Social Commerce",
    growth: "+45%",
    reviews: 1834,
    rating: 4.2,
    link: "https://meesho.com",
    description: "India's fastest-growing social commerce platform",
    trustScore: "Great",
    isRising: true,
    isVerified: true,
    isClaimed: true,
  },
  {
    id: "6",
    name: "Swiggy Instamart",
    category: "Quick Commerce",
    growth: "+38%",
    reviews: 987,
    rating: 4.1,
    link: "https://swiggy.com",
    description: "10-minute grocery delivery across major Indian cities",
    trustScore: "Good",
    isRising: true,
    isVerified: true,
    isClaimed: false,
  },
  {
    id: "7",
    name: "Boat",
    category: "Electronics",
    growth: "+32%",
    reviews: 756,
    rating: 4.3,
    link: "https://boat-lifestyle.com",
    description: "India's leading audio and wearables brand",
    trustScore: "Great",
    isRising: true,
    isVerified: false,
    isClaimed: true,
  },
  {
    id: "8",
    name: "Lenskart",
    category: "Eyewear",
    growth: "+28%",
    reviews: 543,
    rating: 4.0,
    link: "https://lenskart.com",
    description: "India's largest eyewear retailer with home try-on",
    trustScore: "Good",
    isRising: true,
    isVerified: true,
    isClaimed: true,
  },
  {
    id: "9",
    name: "BigBasket",
    category: "Groceries",
    growth: "+25%",
    reviews: 432,
    rating: 4.2,
    link: "https://bigbasket.com",
    description: "India's largest online grocery store",
    trustScore: "Great",
    isRising: true,
    isVerified: true,
    isClaimed: false,
  },
  {
    id: "10",
    name: "Zomato",
    category: "Food Delivery",
    growth: "+22%",
    reviews: 321,
    rating: 3.9,
    link: "https://zomato.com",
    description: "Food delivery and restaurant discovery platform",
    trustScore: "Good",
    isRising: false,
    isVerified: false,
    isClaimed: false,
  },
];

export const howItWorks = [
  {
    step: 1,
    title: "Search & Discover",
    description: "Find stores by category, name, or browse our curated lists of verified retailers",
    icon: Search,
  },
  {
    step: 2,
    title: "Read Reviews",
    description: "Check authentic customer reviews, ratings, and detailed trust scores",
    icon: Eye,
  },
  {
    step: 3,
    title: "Shop Safely",
    description: "Make informed decisions with verified store information and safety ratings",
    icon: Shield,
  },
];

export const industryInsights = [
  {
    title: "Festival Shopping Surge",
    value: "Electronics up 45%",
    description: "Diwali season driving massive growth in electronics and home appliances",
    icon: Monitor,
    trend: "+45%",
    trendColor: "text-green-600",
  },
  {
    title: "Most Popular Category",
    value: "Fashion & Lifestyle",
    description: "Leading category with 3.2M searches this month across India",
    icon: Shirt,
    trend: "3.2M searches",
    trendColor: "text-blue-600",
  },
  {
    title: "Trust Score Average",
    value: "4.3/5.0",
    description: "Indian e-commerce trust rating shows strong consumer confidence",
    icon: Award,
    trend: "+0.4 this month",
    trendColor: "text-green-600",
  },
  {
    title: "Mobile Commerce",
    value: "78% of users",
    description: "Mobile-first shopping dominates Indian e-commerce landscape",
    icon: Activity,
    trend: "+15% vs last year",
    trendColor: "text-green-600",
  },
];

export const successStories = [
  {
    id: "1",
    name: "Arjun P.",
    location: "Bangalore, India",
    story: "StoreRankly helped me identify a fake electronics store that was using stolen product images. The community reviews warned about their poor delivery and fake products. Saved me ₹25,000!",
    outcome: "Avoided scam",
    avatar: "A",
    verified: true,
  },
  {
    id: "2",
    name: "Sneha M.",
    location: "Delhi, India",
    story: "Found an amazing local handicrafts store through StoreRankly's verified listings. The reviews were accurate about their authentic products and fast shipping. Now my go-to for gifts!",
    outcome: "Found trusted store",
    avatar: "S",
    verified: true,
  },
  {
    id: "3",
    name: "Rohit K.",
    location: "Mumbai, India",
    story: "The platform's trust scores helped me choose between similar fashion stores. Went with the higher-rated one and had an excellent experience. The detailed reviews made all the difference.",
    outcome: "Better shopping decision",
    avatar: "R",
    verified: true,
  },
]; 